### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by Saloed** [vyatkinsen/FirstJavaClass#1]
1. Почему все операции возвращают `double`, а не `Numb`? При переводе вашего числа в `double` или `float` сразу теряется весь смысл, поскольку это представление менее точное. 
1. В дальнейшем следите, чтобы результаты сборки (директория target) и настройки вашей среды разработки (.idea) не попадали в репозиторий
2. Для [такого](https://github.com/vyatkinsen/FirstJavaClass/blob/7baea9e52d3075de804d30559f6b8852c3f2eb62/src/test/java/NumbTest.java#L5) лучше использовать импорт
3. А тесты через `maven test` можно запустить? (просто интересно)
4. Кажется `flag` не лучшее название. Может `sign`? [link](https://github.com/vyatkinsen/FirstJavaClass/blob/7baea9e52d3075de804d30559f6b8852c3f2eb62/src/main/java/Numb.java#L8)
5. Если во всех конструкторах вы используете перевод в строку, то почему бы дальше просто не вызывать конструктор из строки?
6. А почему в качестве представления числа строка, а не тот же `List<Integer>` или long? [link](https://github.com/vyatkinsen/FirstJavaClass/blob/7baea9e52d3075de804d30559f6b8852c3f2eb62/src/main/java/Numb.java#L5)
7. Для классов принято указывать наименее специфичный тип. Например [здесь](https://github.com/vyatkinsen/FirstJavaClass/blob/7baea9e52d3075de804d30559f6b8852c3f2eb62/src/main/java/Numb.java#L97) вместо конкретного типа `ArrayList` лучше указать `List`

**Comment by vyatkinsen** [comment]
"А почему в качестве представления числа строка, а не тот же List<Integer> или long?" 
Строка потому, что в дробной части могут быть значащие нули. К примеру, как в этом числе: _123.0003_. Если число сохранять в не строчном варианте, то **нули теряются**.

**Comment by Saloed** [comment]
Вот задание. Жирным выделены несоответствия того, что сделано у вас, и того, что в задании.


Десятичное дробное число с **указанным количеством цифр перед и после запятой**. Формирование строкового представления и установка значения из строки.
Операции сложения, вычитания, умножения (в столбик), деления с округлением по математическим правилам. Операции округления **до указанного числа** десятичных разрядов (по математическим правилам, в сторону 0). 
По умолчанию не предполагается условно бесконечного диапазона размерности (то есть вариант с хранением всего числа как Int или Long принимается). Возможен вариант, когда мы предполагаем этот условно бесконечный диапазон (аналог библиотечного BigDecimal), но он, естественно, на порядок сложнее.
Установка значения из int/long/float/double.
Формирование значения стандартного типа (int/long/float/double).
Не использовать BigDecimal и т.п.

Прочие замечания:
1. А остальные конструкторы куда делись? То что в них можно просто вызвать конструктор из строки, не значит, что они не нужны. [link](https://github.com/vyatkinsen/FirstJavaClass/blob/19d741610f650ab187bb8b61fcec6d006389029b/src/main/java/Numb.java#L11)
2. Вот [этот](https://github.com/vyatkinsen/FirstJavaClass/blob/19d741610f650ab187bb8b61fcec6d006389029b/src/main/java/Numb.java#L27) цикл можно заменить на `substring`.
3. Старайтесь указывать сообщения у исключений. [link](https://github.com/vyatkinsen/FirstJavaClass/blob/19d741610f650ab187bb8b61fcec6d006389029b/src/main/java/Numb.java#L14)
4. При разборе строки было бы хорошо обработать случаи, когда там есть что-то кроме чисел. Сейчас оно сломается, если в начале/конце есть пробелы или есть в fractional части есть что-то кроме чисел.
5. Хранить всё в виде строки это нехорошо, поскольку для любой операции требуется её парсить. (Кажется, это ломает всё, что сделано дальше)


Обычно decimal представляют следующим образом:
1. Всё значение хранится в одном long/biginteger
2. Отдельно хранится значение степени 10
Например, число `1234.567` сохраняют как `value = 1234567, scale = -3`

**Comment by Saloed** [comment]
1. У всех конструкторов есть повторяющаяся часть, где они собирают число из строки. Дублировать такое нехорошо. Лучше вынести это либо в статический либо в обычный метод. 
2. `scale` и `precision` это разные вещи. `precision` это максимальное число знаков после запятой. `scale` это текущее значение степени 10 для вашего `number`. В конструкторе должен указываться именно `precision`. 
3. А зачем [тут](https://github.com/vyatkinsen/FirstJavaClass/blob/7095812c2bbbdc403051b8a1c5b2adf197c789c0/src/main/java/Numb.java#L103) вообще со строкой работать? У вас же после сложения есть новый number и scale. Этого же достаточно, чтобы собрать новый Numb.
4. В остальных операциях аналогично
5. Судя по операции деления, `precision` у вас жёстко забит в коде, и как-то связан вот с [этим](https://github.com/vyatkinsen/FirstJavaClass/blob/7095812c2bbbdc403051b8a1c5b2adf197c789c0/src/main/java/Numb.java#L158) числом 8.
6. Не очень понятно, зачем вам вот [это поле](https://github.com/vyatkinsen/FirstJavaClass/blob/7095812c2bbbdc403051b8a1c5b2adf197c789c0/src/main/java/Numb.java#L4) со строковым представлением
7. Форматирование местами страдает. Где-то есть пробелы вокруг операторов, где-то нет.

**Comment by Saloed** [comment]
1. В конструкторе из double и float дублируются все проверки из конструктора из строки. При этом, они сами переводят число в строку и дальше работают как конструктор из строки. Это можно свести просто к вызову конструктора из строки и убрать весь дублирующийся код. [link](https://github.com/vyatkinsen/FirstJavaClass/blob/45c61f4f21c72fa1c2741061a40ecd7757bd215a/src/main/java/Numb.java#L17)
2. В конструкторах из int и long precision проверять не надо? [link](https://github.com/vyatkinsen/FirstJavaClass/blob/45c61f4f21c72fa1c2741061a40ecd7757bd215a/src/main/java/Numb.java#L33)
3. Может лучше не рассматривать случай, когда есть только целая часть, отдельно, а наоборот, всегда делать, чтобы в строке были и целая и дробная части? Просто при построении из целого числа, докладывать строку из 0? [link](https://github.com/vyatkinsen/FirstJavaClass/blob/45c61f4f21c72fa1c2741061a40ecd7757bd215a/src/main/java/Numb.java#L40)
4. Чем это отличается от случая `precision > length`? [link](https://github.com/vyatkinsen/FirstJavaClass/blob/45c61f4f21c72fa1c2741061a40ecd7757bd215a/src/main/java/Numb.java#L60)
5. Здесь и ниже. Зачем каждый раз собирать Numb из строки, когда у вас уже есть нужный `long number` и `scale`? Лучше добавить приватный конструктор, который позволяет просто выставить эти поля. [link](https://github.com/vyatkinsen/FirstJavaClass/blob/45c61f4f21c72fa1c2741061a40ecd7757bd215a/src/main/java/Numb.java#L101)
6. Попробуйте сделать это без операций со строками. [link](https://github.com/vyatkinsen/FirstJavaClass/blob/45c61f4f21c72fa1c2741061a40ecd7757bd215a/src/main/java/Numb.java#L112)
7. Тут хорошо бы округлить, если число не влезает. [link](https://github.com/vyatkinsen/FirstJavaClass/blob/45c61f4f21c72fa1c2741061a40ecd7757bd215a/src/main/java/Numb.java#L125)
8. Общее замечание. Все математические операции должны работать без преобразования в строку. Строковые операции допустимы только в соответствующем конструкторе.
